version: '3.8'
services:
  common:
    # image: edwardkerckhof/nest-bp-common
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: common
    # mount host directory to docker container, this is done to reflect file changes from host to container
    volumes:
      - ./packages/common:/usr/src/bp/packages/common
    working_dir: /usr/src/bp/packages/common
    command: yarn build:watch

  api:
    # image: edwardkerckhof/nest-bp-api
    build:
      dockerfile: Dockerfile.dev
      context: .
      # builds only up to development stage, this is done for hot reload
      target: api
    # mount host directory to docker container, this is done to reflect file changes from host to container
    volumes:
      - ./packages/api:/usr/src/bp/packages/api
    working_dir: /usr/src/bp/packages/api
    # run in dev mode: yarn start:dev
    # run in debug mode: yarn start:debug --> start vscode debugger first!
    command: yarn start:debug
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_ADMIN_EMAIL: ${DATABASE_ADMIN_EMAIL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000 # api development port
      - 9229:9229 # api debugging port

  app:
    # image: edwardkerckhof/nest-bp-app
    build:
      dockerfile: Dockerfile.dev
      context: .
      # builds only up to development stage, this is done for hot reload
      target: app
    # mount host directory to docker container, this is done to reflect file changes from host to container
    volumes:
      - ./packages/app:/usr/src/bp/packages/app
    working_dir: /usr/src/bp/packages/app
    # run in dev mode: yarn dev
    command: yarn dev
    depends_on:
      - api
    environment:
      PORT: 4200
    ports:
      - 4200:4200 # app development port
    links:
      - api

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PORT: 5432
    ports:
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4:5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5050:80
