############
## COMMON ##
############
# build node image for development
FROM node:14 AS common

# specify working directory
WORKDIR /usr/src/bp

# copy both package.json and .lock file
COPY package.json ./
COPY yarn.lock ./

# copy both package.json and .lock file from all the packages
COPY packages/api/package.json ./packages/api/
COPY packages/api/yarn.lock ./packages/api/
COPY packages/app/package.json ./packages/app/
COPY packages/app/yarn.lock ./packages/app/
COPY packages/common/package.json ./packages/common/

# install dependencies
RUN yarn install

#########
## API ##
#########
# build node image for development
FROM node:14 AS api

# specify working directory
WORKDIR /usr/src/bp

# copy all other files
COPY packages/api/dist ./packages/api/dist
COPY packages/app/dist ./packages/app/dist
COPY packages/common/dist ./packages/common/dist

# copy all other files
COPY --from=common /usr/src/bp .

#########
## APP ##
#########
# build node image for development
FROM node:14 AS app

# specify working directory
WORKDIR /usr/src/bp

# copy all other files
COPY --from=api /usr/src/bp .